version: '3.7'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres

  backend:
    build: .
    depends_on:
      - "db"
    volumes:
      - ./static:/static
    environment: 
      - DB_PASSWORD=${DB_PASSWORD}
      - SMS_API_KEY=${SMS_API_KEY}
    restart: on-failure
    ports:
      - target: 80
        published: 3555
        protocol: tcp
        mode: host

  