version: '3.7'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres

  backend:
    build: .
    environment: 
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - target: 80
        published: 3555
        protocol: tcp
        mode: host

  